name: auth_simple
description: Auth Simple demonstrates how to use the djangoflow_auth package along with additional social authentication packages.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  djangoflow_auth: ^0.2.2
  djangoflow_auth_apple: ^0.0.5+9
  djangoflow_auth_discord: ^0.0.4+10
  djangoflow_auth_facebook: ^0.0.4+9
  djangoflow_auth_google: ^0.0.3+9
  djangoflow_openapi: ^0.0.21
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  flutter_list_bloc: ^4.1.0
  flutter_facebook_auth: ^6.0.0
  firebase_core: ^2.14.0
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.1.4
  hydrated_bloc: ^9.1.1
  json_annotation: ^4.8.1
  list_bloc: ^3.1.0
  openapi_repository_annotations: ^1.2.3
  path_provider: ^2.0.11
  progress_builder: ^1.1.3
  reactive_forms: ^16.0.4
  sign_in_with_apple: ^5.0.0

  # A flutter package for control routing
  auto_route: ^8.0.3

  # A flutter package for chat ui
  flutter_chat_ui: ^1.6.12

  # A Flutter package for scroll controlling
  scroll_to_index: ^3.0.1

  # A Flutter package for socket connection
  djangoflow_websocket: ^0.1.0+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.1
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  icons_launcher: ^2.1.3
  openapi_repository: ^3.3.0
  # A flutter package for generate routes
  auto_route_generator: ^8.0.0


dependency_overrides:
  # use local dependency for djangoflow_openapi to override the one from pub.dev
  djangoflow_openapi:
    path: ./packages/djangoflow_openapi
  oauth2_client:
    git:
      url: https://github.com/jheld/oauth2_client.git
      ref: master

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo/
