name: djangoflow_openapi
version: 1.0.0
description: OpenAPI API client
homepage: homepage

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.4.2+1
  json_annotation: ^4.8.1
  retrofit: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  test: ^1.16.0


